package db.pojos;
// Generated 5/04/2014 12:20:41 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Calificacion generated by hbm2java
 */
public class Calificacion  implements java.io.Serializable {


     private Integer idCalificacion;
     private Calificadora calificadora;
     private String calificacion;
     private Set vectorsForIdCalificacionHr = new HashSet(0);
     private Set vectorsForIdCalificacionFitch = new HashSet(0);
     private Set vectorsForIdCalificacionSp = new HashSet(0);
     private Set vectorsForIdCalificacionMoody = new HashSet(0);

    public Calificacion() {
    }

    public Calificacion(Calificadora calificadora, String calificacion, Set vectorsForIdCalificacionHr, Set vectorsForIdCalificacionFitch, Set vectorsForIdCalificacionSp, Set vectorsForIdCalificacionMoody) {
       this.calificadora = calificadora;
       this.calificacion = calificacion;
       this.vectorsForIdCalificacionHr = vectorsForIdCalificacionHr;
       this.vectorsForIdCalificacionFitch = vectorsForIdCalificacionFitch;
       this.vectorsForIdCalificacionSp = vectorsForIdCalificacionSp;
       this.vectorsForIdCalificacionMoody = vectorsForIdCalificacionMoody;
    }
   
    public Integer getIdCalificacion() {
        return this.idCalificacion;
    }
    
    public void setIdCalificacion(Integer idCalificacion) {
        this.idCalificacion = idCalificacion;
    }
    public Calificadora getCalificadora() {
        return this.calificadora;
    }
    
    public void setCalificadora(Calificadora calificadora) {
        this.calificadora = calificadora;
    }
    public String getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(String calificacion) {
        this.calificacion = calificacion;
    }
    public Set getVectorsForIdCalificacionHr() {
        return this.vectorsForIdCalificacionHr;
    }
    
    public void setVectorsForIdCalificacionHr(Set vectorsForIdCalificacionHr) {
        this.vectorsForIdCalificacionHr = vectorsForIdCalificacionHr;
    }
    public Set getVectorsForIdCalificacionFitch() {
        return this.vectorsForIdCalificacionFitch;
    }
    
    public void setVectorsForIdCalificacionFitch(Set vectorsForIdCalificacionFitch) {
        this.vectorsForIdCalificacionFitch = vectorsForIdCalificacionFitch;
    }
    public Set getVectorsForIdCalificacionSp() {
        return this.vectorsForIdCalificacionSp;
    }
    
    public void setVectorsForIdCalificacionSp(Set vectorsForIdCalificacionSp) {
        this.vectorsForIdCalificacionSp = vectorsForIdCalificacionSp;
    }
    public Set getVectorsForIdCalificacionMoody() {
        return this.vectorsForIdCalificacionMoody;
    }
    
    public void setVectorsForIdCalificacionMoody(Set vectorsForIdCalificacionMoody) {
        this.vectorsForIdCalificacionMoody = vectorsForIdCalificacionMoody;
    }




}


