package db.pojos;
// Generated 20/02/2014 10:47:13 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Catalogocuenta generated by hbm2java
 */
public class Catalogocuenta  implements java.io.Serializable {


     private Integer idCatalogoCuenta;
     private String desCatalogoCuenta;
     private Set cuentas = new HashSet(0);

    public Catalogocuenta() {
    }

	
    public Catalogocuenta(String desCatalogoCuenta) {
        this.desCatalogoCuenta = desCatalogoCuenta;
    }
    public Catalogocuenta(String desCatalogoCuenta, Set cuentas) {
       this.desCatalogoCuenta = desCatalogoCuenta;
       this.cuentas = cuentas;
    }
   
    public Integer getIdCatalogoCuenta() {
        return this.idCatalogoCuenta;
    }
    
    public void setIdCatalogoCuenta(Integer idCatalogoCuenta) {
        this.idCatalogoCuenta = idCatalogoCuenta;
    }
    public String getDesCatalogoCuenta() {
        return this.desCatalogoCuenta;
    }
    
    public void setDesCatalogoCuenta(String desCatalogoCuenta) {
        this.desCatalogoCuenta = desCatalogoCuenta;
    }
    public Set getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set cuentas) {
        this.cuentas = cuentas;
    }




}


