package db.pojos;
// Generated 25/02/2014 09:45:45 PM by Hibernate Tools 3.6.0

import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.click.control.ActionLink;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta implements java.io.Serializable, Cloneable {

    private Long idCuenta;
    private Moneda moneda;
    private Regcuenta regcuenta;
    private Catalogocuenta catalogocuenta;
    private Double valor;
    private String ref;
    private Integer status;
    private ActionLink actionLink;

    public Cuenta() {
    }

    public Cuenta(Moneda moneda, Regcuenta regcuenta, Catalogocuenta catalogocuenta) {
        this.moneda = moneda;
        this.regcuenta = regcuenta;
        this.catalogocuenta = catalogocuenta;
    }

    public Cuenta(Moneda moneda, Regcuenta regcuenta, Catalogocuenta catalogocuenta, Double valor, String ref, Integer status) {
        this.moneda = moneda;
        this.regcuenta = regcuenta;
        this.catalogocuenta = catalogocuenta;
        this.valor = valor;
        this.ref = ref;
        this.status = status;
    }

    public Long getIdCuenta() {
        return this.idCuenta;
    }

    public void setIdCuenta(Long idCuenta) {
        this.idCuenta = idCuenta;
    }

    public Moneda getMoneda() {
        return this.moneda;
    }

    public void setMoneda(Moneda moneda) {
        this.moneda = moneda;
    }

    public Regcuenta getRegcuenta() {
        return this.regcuenta;
    }

    public void setRegcuenta(Regcuenta regcuenta) {
        this.regcuenta = regcuenta;
    }

    public Catalogocuenta getCatalogocuenta() {
        return this.catalogocuenta;
    }
    
    public String getEjercicio(){
        return this.getRegcuenta().getDesRegCuenta();
    }

    public void setCatalogocuenta(Catalogocuenta catalogocuenta) {
        this.catalogocuenta = catalogocuenta;
    }

    public Double getValor() {
        return this.valor;
    }

    public void setValor(Double valor) {
        this.valor = valor;
    }

    public String getRef() {
        return this.ref;
    }

    public void setRef(String ref) {
        this.ref = ref;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public static String[] getColumns() {
        return new String[]{"Ejercicio", "Descripcion", "Resultado*"};
    }
    

    /**
     * @return the actionLink
     */
    public ActionLink getActionLink() {
        return actionLink;
    }

    /**
     * @param actionLink the actionLink to set
     */
    public void setActionLink(ActionLink actionLink) {
        this.actionLink = actionLink;
    }

    public Object clone() throws CloneNotSupportedException {
        return super.clone();
    }

    public String getDescripcion() {
        return this.catalogocuenta.getDesCatalogoCuenta();
    }

    public String getResultado() {
            Locale loc=new Locale("us");
            NumberFormat instance = NumberFormat.getInstance(loc);
            System.out.println("sacando valor");
            return  instance.format(getValor())+ " " + getMoneda().getDesMoneda();
        
    }
    
    public static void main(String[] args) {
            Locale loc=new Locale("us");
            NumberFormat instance = NumberFormat.getInstance(loc);
            System.out.println(instance.format(534234.123));
    }
}
