package db.pojos;
// Generated Feb 4, 2014 11:00:14 PM by Hibernate Tools 3.6.0



/**
 * Cuenta generated by hbm2java
 */
public class Cuenta  implements java.io.Serializable {


     private Integer idCuenta;
     private Double valor;
     private String ref;
     private String descripcion;
     private Integer status;

    public Cuenta() {
    }

    public Cuenta(Double valor, String ref, String descripcion, Integer status) {
       this.valor = valor;
       this.ref = ref;
       this.descripcion = descripcion;
       this.status = status;
    }
   
    public Integer getIdCuenta() {
        return this.idCuenta;
    }
    
    public void setIdCuenta(Integer idCuenta) {
        this.idCuenta = idCuenta;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }
    public String getRef() {
        return this.ref;
    }
    
    public void setRef(String ref) {
        this.ref = ref;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }


    public static String[] getColumns(){
        return new String[]{"Descripcion","Valor"};
    }


}


