package db.pojos;
// Generated Feb 4, 2014 11:00:14 PM by Hibernate Tools 3.6.0

import org.apache.click.control.ActionLink;




/**
 * Cuenta generated by hbm2java
 */
public class Cuenta  implements java.io.Serializable,Cloneable {


     private Integer idCuenta;
     private Double valor;
     private String ref;
     private String descripcion;
     private Integer status;
     private ActionLink actionLink;
     
    public Cuenta() {
    }

    public Cuenta(Double valor, String ref, String descripcion, Integer status) {
       this.valor = valor;
       this.ref = ref;
       this.descripcion = descripcion;
       this.status = status;
    }
   
    public Integer getIdCuenta() {
        return this.idCuenta;
    }
    
    public void setIdCuenta(Integer idCuenta) {
        this.idCuenta = idCuenta;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }
    public String getRef() {
        return this.ref;
    }
    
    public void setRef(String ref) {
        this.ref = ref;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }


    public static String[] getColumns(){
        return new String[]{"Descripcion","Valor"};
    }

    /**
     * @return the actionLink
     */
    public ActionLink getActionLink() {
        return actionLink;
    }

    /**
     * @param actionLink the actionLink to set
     */
    public void setActionLink(ActionLink actionLink) {
        this.actionLink = actionLink;
    }

    public Object clone() throws CloneNotSupportedException{
        return super.clone();
    }
    
}


