package db.pojos;
// Generated 25/02/2014 09:45:45 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Regcuenta generated by hbm2java
 */
public class Regcuenta  implements java.io.Serializable {


     private Integer idRegCuenta;
     private String desRegCuenta;
     private Set cuentas = new HashSet(0);

    public Regcuenta() {
    }

	
    public Regcuenta(String desRegCuenta) {
        this.desRegCuenta = desRegCuenta;
    }
    public Regcuenta(String desRegCuenta, Set cuentas) {
       this.desRegCuenta = desRegCuenta;
       this.cuentas = cuentas;
    }
   
    public Integer getIdRegCuenta() {
        return this.idRegCuenta;
    }
    
    public void setIdRegCuenta(Integer idRegCuenta) {
        this.idRegCuenta = idRegCuenta;
    }
    public String getDesRegCuenta() {
        return this.desRegCuenta;
    }
    
    public void setDesRegCuenta(String desRegCuenta) {
        this.desRegCuenta = desRegCuenta;
    }
    public Set getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set cuentas) {
        this.cuentas = cuentas;
    }




}


