package db.pojos;
// Generated 30/03/2014 11:04:46 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Regcuenta generated by hbm2java
 */
public class Regcuenta  implements java.io.Serializable,Cloneable {


     private Integer idRegCuenta;
     private String desRegCuenta;
     private Date fecha;
     private Set regcuentausers = new HashSet(0);
     private Set cuentas = new HashSet(0);

    public Regcuenta() {
    }

	
    public Regcuenta(String desRegCuenta) {
        this.desRegCuenta = desRegCuenta;
    }
    public Regcuenta(String desRegCuenta, Date fecha, Set regcuentausers, Set cuentas) {
       this.desRegCuenta = desRegCuenta;
       this.fecha = fecha;
       this.regcuentausers = regcuentausers;
       this.cuentas = cuentas;
    }
   
    public Integer getIdRegCuenta() {
        return this.idRegCuenta;
    }
    
    public void setIdRegCuenta(Integer idRegCuenta) {
        this.idRegCuenta = idRegCuenta;
    }
    public String getDesRegCuenta() {
        return this.desRegCuenta;
    }
    
    public void setDesRegCuenta(String desRegCuenta) {
        this.desRegCuenta = desRegCuenta;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getRegcuentausers() {
        return this.regcuentausers;
    }
    
    public void setRegcuentausers(Set regcuentausers) {
        this.regcuentausers = regcuentausers;
    }
    public Set getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set cuentas) {
        this.cuentas = cuentas;
    }


     @Override
    public String toString(){
        return String.valueOf(idRegCuenta);
    }

     @Override
    public Object clone() throws CloneNotSupportedException{
        return super.clone();
    }
    
}


