package db.pojos;
// Generated 5/04/2014 12:20:41 AM by Hibernate Tools 3.6.0



/**
 * Tenencia generated by hbm2java
 */
public class Tenencia  implements java.io.Serializable {


     private Integer id;

    public Tenencia() {
    }

   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }




}


