package db.pojos;
// Generated 5/04/2014 12:20:41 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Vector generated by hbm2java
 */
public class Vector  implements java.io.Serializable {


     private Integer idVector;
     private Calificacion calificacionByIdCalificacionHr;
     private Tipotasa tipotasa;
     private Calificacion calificacionByIdCalificacionMoody;
     private Calificacion calificacionByIdCalificacionSp;
     private Calificacion calificacionByIdCalificacionFitch;
     private String idTipoInstrumento;
     private String emisioraInstrumento;
     private String serieInstrumento;
     private Double tasaInstrumento;
     private Double precioSucio;
     private Double precioLimpio;
     private Integer duracion;
     private Date fecha;

    public Vector() {
    }

	
    public Vector(Date fecha) {
        this.fecha = fecha;
    }
    public Vector(Calificacion calificacionByIdCalificacionHr, Tipotasa tipotasa, Calificacion calificacionByIdCalificacionMoody, Calificacion calificacionByIdCalificacionSp, Calificacion calificacionByIdCalificacionFitch, String idTipoInstrumento, String emisioraInstrumento, String serieInstrumento, Double tasaInstrumento, Double precioSucio, Double precioLimpio, Integer duracion, Date fecha) {
       this.calificacionByIdCalificacionHr = calificacionByIdCalificacionHr;
       this.tipotasa = tipotasa;
       this.calificacionByIdCalificacionMoody = calificacionByIdCalificacionMoody;
       this.calificacionByIdCalificacionSp = calificacionByIdCalificacionSp;
       this.calificacionByIdCalificacionFitch = calificacionByIdCalificacionFitch;
       this.idTipoInstrumento = idTipoInstrumento;
       this.emisioraInstrumento = emisioraInstrumento;
       this.serieInstrumento = serieInstrumento;
       this.tasaInstrumento = tasaInstrumento;
       this.precioSucio = precioSucio;
       this.precioLimpio = precioLimpio;
       this.duracion = duracion;
       this.fecha = fecha;
    }
   
    public Integer getIdVector() {
        return this.idVector;
    }
    
    public void setIdVector(Integer idVector) {
        this.idVector = idVector;
    }
    public Calificacion getCalificacionByIdCalificacionHr() {
        return this.calificacionByIdCalificacionHr;
    }
    
    public void setCalificacionByIdCalificacionHr(Calificacion calificacionByIdCalificacionHr) {
        this.calificacionByIdCalificacionHr = calificacionByIdCalificacionHr;
    }
    public Tipotasa getTipotasa() {
        return this.tipotasa;
    }
    
    public void setTipotasa(Tipotasa tipotasa) {
        this.tipotasa = tipotasa;
    }
    public Calificacion getCalificacionByIdCalificacionMoody() {
        return this.calificacionByIdCalificacionMoody;
    }
    
    public void setCalificacionByIdCalificacionMoody(Calificacion calificacionByIdCalificacionMoody) {
        this.calificacionByIdCalificacionMoody = calificacionByIdCalificacionMoody;
    }
    public Calificacion getCalificacionByIdCalificacionSp() {
        return this.calificacionByIdCalificacionSp;
    }
    
    public void setCalificacionByIdCalificacionSp(Calificacion calificacionByIdCalificacionSp) {
        this.calificacionByIdCalificacionSp = calificacionByIdCalificacionSp;
    }
    public Calificacion getCalificacionByIdCalificacionFitch() {
        return this.calificacionByIdCalificacionFitch;
    }
    
    public void setCalificacionByIdCalificacionFitch(Calificacion calificacionByIdCalificacionFitch) {
        this.calificacionByIdCalificacionFitch = calificacionByIdCalificacionFitch;
    }
    public String getIdTipoInstrumento() {
        return this.idTipoInstrumento;
    }
    
    public void setIdTipoInstrumento(String idTipoInstrumento) {
        this.idTipoInstrumento = idTipoInstrumento;
    }
    public String getEmisioraInstrumento() {
        return this.emisioraInstrumento;
    }
    
    public void setEmisioraInstrumento(String emisioraInstrumento) {
        this.emisioraInstrumento = emisioraInstrumento;
    }
    public String getSerieInstrumento() {
        return this.serieInstrumento;
    }
    
    public void setSerieInstrumento(String serieInstrumento) {
        this.serieInstrumento = serieInstrumento;
    }
    public Double getTasaInstrumento() {
        return this.tasaInstrumento;
    }
    
    public void setTasaInstrumento(Double tasaInstrumento) {
        this.tasaInstrumento = tasaInstrumento;
    }
    public Double getPrecioSucio() {
        return this.precioSucio;
    }
    
    public void setPrecioSucio(Double precioSucio) {
        this.precioSucio = precioSucio;
    }
    public Double getPrecioLimpio() {
        return this.precioLimpio;
    }
    
    public void setPrecioLimpio(Double precioLimpio) {
        this.precioLimpio = precioLimpio;
    }
    public Integer getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Integer duracion) {
        this.duracion = duracion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


